-- Created by Redgate Data Modeler (https://datamodeler.redgate-platform.com)
-- Last modification date: 2026-06-01 00:41:07.736

DROP TABLE Championships;
DROP TABLE Pit_Stops;
DROP TABLE Race_Stewards;
DROP TABLE Race_Officials;
DROP TABLE Results;
DROP TABLE Driver_Team;
DROP TABLE Drivers;
DROP TABLE Teams;
DROP TABLE Races;
DROP TABLE Circuits;

CREATE TABLE Circuits (
    circuit_id    INTEGER          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR2(100)    NOT NULL,
    location      VARCHAR2(100)    NOT NULL,
    country       VARCHAR2(50)     NOT NULL,
    length_km     NUMBER(5,3)      NOT NULL,
    total_laps    INTEGER          NOT NULL,
    circuit_type  VARCHAR2(20)     DEFAULT 'permanent' NOT NULL,
    CONSTRAINT AK_circuits_name    UNIQUE (name),
    CONSTRAINT chk_length          CHECK (length_km > 0),
    CONSTRAINT chk_laps            CHECK (total_laps > 0),
    CONSTRAINT chk_circuit_type    CHECK (circuit_type IN ('permanent','street','hybrid')),
    CONSTRAINT Circuits_pk         PRIMARY KEY (circuit_id)
);

CREATE TABLE Teams (
    team_id                    INTEGER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                       VARCHAR2(100)  NOT NULL,
    base_country               VARCHAR2(50)   NOT NULL,
    constructors_championships INTEGER        DEFAULT 0 NOT NULL,
    founded_year               INTEGER        NOT NULL,
    CONSTRAINT AK_teams_name           UNIQUE (name),
    CONSTRAINT chk_titles              CHECK (constructors_championships >= 0),
    CONSTRAINT chk_founded_year_min    CHECK (founded_year >= 1950),
    CONSTRAINT Teams_pk                PRIMARY KEY (team_id)
);

CREATE TABLE Drivers (
    driver_id      INTEGER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name     VARCHAR2(50)   NOT NULL,
    last_name      VARCHAR2(50)   NOT NULL,
    date_of_birth  DATE           NOT NULL,
    nationality    VARCHAR2(50)   NOT NULL,
    license_number VARCHAR2(20)   NOT NULL,
    career_points  NUMBER(10,1)   DEFAULT 0 NOT NULL,
    CONSTRAINT AK_drivers_license      UNIQUE (license_number),
    CONSTRAINT chk_driver_points       CHECK (career_points >= 0),
    CONSTRAINT Drivers_pk              PRIMARY KEY (driver_id)
);

CREATE TABLE Driver_Team (
    driver_team_id  INTEGER   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    driver_id       INTEGER   NOT NULL,
    team_id         INTEGER   NOT NULL,
    season_year     INTEGER   NOT NULL,
    car_number      INTEGER   NOT NULL,
    joined_date     DATE      NOT NULL,
    left_date       DATE      NULL,
    CONSTRAINT uq_driver_season        UNIQUE (driver_id, season_year),
    CONSTRAINT uq_team_car_season      UNIQUE (team_id, car_number, season_year),
    CONSTRAINT chk_dt_season           CHECK (season_year >= 1950),
    CONSTRAINT chk_car                 CHECK (car_number BETWEEN 0 AND 99),
    CONSTRAINT chk_dates               CHECK (left_date IS NULL OR left_date >= joined_date),
    CONSTRAINT Driver_Team_pk          PRIMARY KEY (driver_team_id),
    CONSTRAINT fk_dt_driver            FOREIGN KEY (driver_id)
        REFERENCES Drivers (driver_id) ON DELETE CASCADE,
    CONSTRAINT fk_dt_team              FOREIGN KEY (team_id)
        REFERENCES Teams (team_id) ON DELETE CASCADE
);

CREATE TABLE Races (
    race_id       INTEGER        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    circuit_id    INTEGER        NOT NULL,
    season_year   INTEGER        NOT NULL,
    round_number  INTEGER        NOT NULL,
    name          VARCHAR2(100)  NOT NULL,
    race_date     DATE           NOT NULL,
    status        VARCHAR2(20)   DEFAULT 'scheduled' NOT NULL,
    CONSTRAINT uq_race_season_round    UNIQUE (season_year, round_number),
    CONSTRAINT chk_season              CHECK (season_year >= 1950),
    CONSTRAINT chk_round               CHECK (round_number BETWEEN 1 AND 30),
    CONSTRAINT chk_race_status         CHECK (status IN ('scheduled','completed','cancelled')),
    CONSTRAINT Races_pk                PRIMARY KEY (race_id),
    CONSTRAINT fk_race_circuit         FOREIGN KEY (circuit_id)
        REFERENCES Circuits (circuit_id) ON DELETE CASCADE
);

CREATE TABLE Results (
    result_id          INTEGER       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    race_id            INTEGER       NOT NULL,
    driver_id          INTEGER       NOT NULL,
    team_id            INTEGER       NOT NULL,
    grid_position      INTEGER       NULL,
    finish_position    INTEGER       NULL,
    points_awarded     INTEGER       DEFAULT 0 NOT NULL,
    status             VARCHAR2(30)  NOT NULL,
    fastest_lap_rank   INTEGER       NULL,
    race_time_seconds  NUMBER(10,3)  NULL,
    CONSTRAINT uq_race_driver      UNIQUE (race_id, driver_id),
    CONSTRAINT uq_race_finish      UNIQUE (race_id, finish_position),
    CONSTRAINT chk_grid            CHECK (grid_position IS NULL OR grid_position > 0),
    CONSTRAINT chk_finish          CHECK (finish_position IS NULL OR finish_position > 0),
    CONSTRAINT chk_points          CHECK (points_awarded >= 0),
    CONSTRAINT chk_flr             CHECK (fastest_lap_rank IS NULL OR fastest_lap_rank > 0),
    CONSTRAINT chk_time            CHECK (race_time_seconds IS NULL OR race_time_seconds > 0),
    CONSTRAINT chk_result_status   CHECK (status IN ('finished','dnf','dns','dsq','lapped')),
    CONSTRAINT Results_pk          PRIMARY KEY (result_id),
    CONSTRAINT fk_res_driver       FOREIGN KEY (driver_id)
        REFERENCES Drivers (driver_id) ON DELETE CASCADE,
    CONSTRAINT fk_res_race         FOREIGN KEY (race_id)
        REFERENCES Races (race_id) ON DELETE CASCADE,
    CONSTRAINT fk_res_team         FOREIGN KEY (team_id)
        REFERENCES Teams (team_id) ON DELETE CASCADE
);

CREATE TABLE Pit_Stops (
    pit_stop_id       INTEGER       NOT NULL,
    stop_number       INTEGER       NOT NULL,
    lap_number        INTEGER       NOT NULL,
    duration_seconds  NUMBER(6,3)   NOT NULL,
    tyre_compound     VARCHAR2(20)  NOT NULL,
    driver_id         INTEGER       NOT NULL,
    race_id           INTEGER       NOT NULL,
    result_id         INTEGER       NOT NULL,
    CONSTRAINT Pit_Stops_pk        PRIMARY KEY (pit_stop_id),
    CONSTRAINT Pit_Stops_Drivers     FOREIGN KEY (driver_id)
        REFERENCES Drivers (driver_id),
    CONSTRAINT Pit_Stops_Races       FOREIGN KEY (race_id)
        REFERENCES Races (race_id),
    CONSTRAINT Pit_Stops_Results     FOREIGN KEY (result_id)
        REFERENCES Results (result_id)
);

CREATE TABLE Race_Officials (
    race_officials_id  INTEGER       NOT NULL,
    first_name         VARCHAR2(20)  NOT NULL,
    last_name          VARCHAR2(20)  NOT NULL,
    role               VARCHAR2(40)  NOT NULL,
    nationality        VARCHAR2(40)  NOT NULL,
    license_number     INTEGER       NOT NULL,
    CONSTRAINT Race_Officials_pk PRIMARY KEY (race_officials_id)
);

CREATE TABLE Race_Stewards (
    steward_id         INTEGER        NOT NULL,
    race_officials_id  INTEGER        NOT NULL,
    race_id            INTEGER        NOT NULL,
    assigned_date      DATE           NOT NULL,
    notes              VARCHAR2(100)  NOT NULL,
    CONSTRAINT Race_Stewards_pk              PRIMARY KEY (steward_id),
    CONSTRAINT Race_Stewards_Race_Officials  FOREIGN KEY (race_officials_id)
        REFERENCES Race_Officials (race_officials_id),
    CONSTRAINT Race_Stewards_Races           FOREIGN KEY (race_id)
        REFERENCES Races (race_id)
);

CREATE TABLE Championships (
    championships_id  INTEGER       NOT NULL,
    driver_id         INTEGER       NOT NULL,
    driver_team_id    INTEGER       NOT NULL,
    season_year       INTEGER       NOT NULL,
    type              VARCHAR2(20)  NOT NULL,
    total_points      INTEGER       NOT NULL,
    wins              INTEGER       NOT NULL,
    rank              INTEGER       NOT NULL,
    CONSTRAINT Championships_pk          PRIMARY KEY (championships_id),
    CONSTRAINT Championships_Drivers     FOREIGN KEY (driver_id)
        REFERENCES Drivers (driver_id),
    CONSTRAINT Championships_Driver_Team FOREIGN KEY (driver_team_id)
        REFERENCES Driver_Team (driver_team_id)
);